# Generated by Django 4.0.5 on 2022-11-02 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waiting',
            old_name='wating',
            new_name='waiting',
        ),
    ]
